name: cpa_rewards_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  web_browser_detect: ^2.0.3  # For device detection
  geolocator: ^13.0.2         # For country detection
  url_launcher: ^6.3.1       # For opening offers
  flutter_paypal: ^0.2.1      # For PayPal payments
  firebase_core: ^3.11.0
  geocoding: ^3.0.0
  flutter_inappwebview: ^6.1.5
  device_info_plus: ^11.3.0
  cloud_firestore: ^5.6.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/gift_icon.png
